# 📊 Exploração dos Datasets - DataOps Governance Lab

Este notebook demonstra como carregar e explorar os datasets do projeto **TechCommerce** utilizados no curso de DataOps: Governança e Qualidade de Dados.

## 🎯 Objetivos
- Carregar os 4 datasets principais do projeto
- Verificar a estrutura e quantidade de registros
- Realizar uma análise inicial dos dados
- Identificar possíveis problemas de qualidade

## 📚 Importação das Bibliotecas

Primeiro, importamos a biblioteca **pandas** que será utilizada para manipulação e análise dos dados.

In [3]:
import pandas as pd
import os

# Configuração para melhor visualização dos DataFrames
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', 50)

## 📁 Carregamento dos Datasets

Os datasets estão localizados na pasta `datasets/` e representam diferentes aspectos do negócio da **TechCommerce**:

- **clientes.csv**: Informações dos clientes
- **produtos.csv**: Catálogo de produtos
- **vendas.csv**: Transações de vendas
- **logistica.csv**: Dados de entrega e logística

In [ ]:
# Definir o caminho base para os datasets
base_path = './datasets/'

# Carregar cada dataset usando pandas
clientes = pd.read_csv(f'{base_path}clientes.csv')
produtos = pd.read_csv(f'{base_path}produtos.csv')
vendas = pd.read_csv(f'{base_path}vendas.csv')
logistica = pd.read_csv(f'{base_path}logistica.csv')

## 📊 Análise Quantitativa dos Datasets

Vamos verificar a quantidade de registros em cada dataset para ter uma visão geral do volume de dados.

In [5]:
# Exibir a quantidade de registros em cada dataset
print(f"📋 Resumo dos Datasets:")
print(f"{'='*50}")
print(f"Clientes: {len(clientes)} registros")
print(f"Produtos: {len(produtos)} registros")
print(f"Vendas: {len(vendas)} registros")
print(f"Logística: {len(logistica)} registros")
print(f"{'='*50}")
print(f"Total de registros: {len(clientes) + len(produtos) + len(vendas) + len(logistica)}")

📋 Resumo dos Datasets:
==================================================
Clientes: 16 registros
Produtos: 20 registros
Vendas: 25 registros
Logística: 22 registros
==================================================
Total de registros: 83

## 🔍 Exploração Detalhada por Dataset

Agora vamos analisar cada dataset individualmente para entender sua estrutura e identificar possíveis problemas de qualidade.

### 👥 Dataset: Clientes

Contém informações dos clientes da TechCommerce.

In [6]:
print("📋 DATASET: CLIENTES")
print("="*50)
print(f"Dimensões: {clientes.shape}")
print(f"Colunas: {list(clientes.columns)}")
print("\n📊 Primeiros 5 registros:")
display(clientes.head())

print("\n🔍 Informações do Dataset:")
clientes.info()

print("\n⚠️ Valores Nulos:")
print(clientes.isnull().sum())

📋 DATASET: CLIENTES
==================================================
Dimensões: (16, 8)
Colunas: ['id_cliente', 'nome', 'email', 'telefone', 'data_nascimento', 'cidade', 'estado', 'data_cadastro']

📊 Primeiros 5 registros:

,id_cliente,nome,email,telefone,data_nascimento,cidade,estado,data_cadastro
0,1,João Silva,joao@email.com,11999887766,1985-03-15,São Paulo,SP,2023-01-10
1,2,Maria Santos,NaN,11888776655,1990-07-22,Rio de Janeiro,RJ,2023-01-15
2,1,João Silva,joao@email.com,11999887766,1985-03-15,São Paulo,SP,2023-01-10
3,3,Pedro,pedro@invalid,119999,2000-12-01,Belo Horizonte,MG,2023-02-01
4,4,NaN,ana@email.com,11777665544,1995-05-30,São Paulo,SP,2023-02-10

🔍 Informações do Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_cliente       16 non-null     int64
 1   nome             14 non-null     object
 2   email            14 non-null     object
 3   telefone         16 non-null     int64
 4   data_nascimento  16 non-null     object
 5   cidade           16 non-null     object
 6   estado           16 non-null     object
 7   data_cadastro    16 non-null     object
dtypes: int64(2), object(6)
memory usage: 1.1+ KB

⚠️ Valores Nulos:
id_cliente         0
nome               2
email              2
telefone           0
data_nascimento    0
cidade             0
estado             0
data_cadastro      0
dtype: int64

### 🛍️ Dataset: Produtos

Catálogo de produtos disponíveis na loja.

In [7]:
print("📋 DATASET: PRODUTOS")
print("="*50)
print(f"Dimensões: {produtos.shape}")
print(f"Colunas: {list(produtos.columns)}")
print("\n📊 Primeiros 5 registros:")
display(produtos.head())

print("\n🔍 Informações do Dataset:")
produtos.info()

print("\n⚠️ Valores Nulos:")
print(produtos.isnull().sum())

📋 DATASET: PRODUTOS
==================================================
Dimensões: (20, 7)
Colunas: ['id_produto', 'nome_produto', 'categoria', 'preco', 'estoque', 'data_criacao', 'ativo']

📊 Primeiros 5 registros:

,id_produto,nome_produto,categoria,preco,estoque,data_criacao,ativo
0,101,Smartphone XYZ,Eletrônicos,899.99,50,2023-01-01,True
1,102,Notebook ABC,NaN,1299.99,25,2023-01-05,True
2,103,Mouse Gamer,Informática,-29.99,100,2023-01-10,True
3,104,Teclado Mecânico,Informática,199.99,0,2023-01-15,False
4,105,Smartphone XYZ,Eletrônicos,899.99,50,2023-01-01,True

🔍 Informações do Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_produto    20 non-null     int64
 1   nome_produto  19 non-null     object
 2   categoria     19 non-null     object
 3   preco         20 non-null     float64
 4   estoque       20 non-null     int64
 5   data_criacao  20 non-null     object
 6   ativo         20 non-null     bool
dtypes: bool(1), float64(1), int64(2), object(3)
memory usage: 1.1+ KB

⚠️ Valores Nulos:
id_produto      0
nome_produto    1
categoria       1
preco           0
estoque         0
data_criacao    0
ativo           0
dtype: int64

### 💰 Dataset: Vendas

Transações de vendas realizadas na plataforma.

In [8]:
print("📋 DATASET: VENDAS")
print("="*50)
print(f"Dimensões: {vendas.shape}")
print(f"Colunas: {list(vendas.columns)}")
print("\n📊 Primeiros 5 registros:")
display(vendas.head())

print("\n🔍 Informações do Dataset:")
vendas.info()

print("\n⚠️ Valores Nulos:")
print(vendas.isnull().sum())

📋 DATASET: VENDAS
==================================================
Dimensões: (25, 8)
Colunas: ['id_venda', 'id_cliente', 'id_produto', 'quantidade', 'valor_unitario', 'valor_total', 'data_venda', 'status']

📊 Primeiros 5 registros:

,id_venda,id_cliente,id_produto,quantidade,valor_unitario,valor_total,data_venda,status
0,1001,1,101,2,899.99,1799.98,2023-03-01,Concluída
1,1002,2,102,1,1299.99,1299.99,2023-03-02,Pendente
2,1003,999,103,3,29.99,89.97,2023-03-03,Concluída
3,1004,1,104,-1,199.99,-199.99,2023-03-04,Cancelada
4,1005,3,101,1,899.99,899.99,2024-12-31,Processando

🔍 Informações do Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_venda        25 non-null     int64
 1   id_cliente      25 non-null     int64
 2   id_produto      25 non-null     int64
 3   quantidade      25 non-null     int64
 4   valor_unitario  25 non-null     float64
 5   valor_total     25 non-null     float64
 6   data_venda      25 non-null     object
 7   status          25 non-null     object
dtypes: float64(2), int64(4), object(2)
memory usage: 1.7+ KB

⚠️ Valores Nulos:
id_venda          0
id_cliente        0
id_produto        0
quantidade        0
valor_unitario    0
valor_total       0
data_venda        0
status            0
dtype: int64

### 🚚 Dataset: Logística

Dados de entrega e logística dos pedidos.

In [9]:
print("📋 DATASET: LOGÍSTICA")
print("="*50)
print(f"Dimensões: {logistica.shape}")
print(f"Colunas: {list(logistica.columns)}")
print("\n📊 Primeiros 5 registros:")
display(logistica.head())

print("\n🔍 Informações do Dataset:")
logistica.info()

print("\n⚠️ Valores Nulos:")
print(logistica.isnull().sum())

📋 DATASET: LOGÍSTICA
==================================================
Dimensões: (22, 7)
Colunas: ['id_entrega', 'id_venda', 'transportadora', 'data_envio', 'data_entrega_prevista', 'data_entrega_real', 'status_entrega']

📊 Primeiros 5 registros:

,id_entrega,id_venda,transportadora,data_envio,data_entrega_prevista,data_entrega_real,status_entrega
0,2001,1001,Correios,2023-03-02,2023-03-05,2023-03-04,Entregue
1,2002,1002,Transportadora XYZ,2023-03-03,NaN,2023-03-10,Entregue
2,2003,1003,Correios,2023-03-04,2023-03-07,NaN,Em Trânsito
3,2004,1004,NaN,NaN,NaN,NaN,Cancelada
4,2005,1006,Correios,2023-03-07,2023-03-10,2023-03-09,Entregue

🔍 Informações do Dataset:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 7 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id_entrega             22 non-null     int64
 1   id_venda               22 non-null     int64
 2   transportadora         20 non-null     object
 3   data_envio             21 non-null     object
 4   data_entrega_prevista  20 non-null     object
 5   data_entrega_real      17 non-null     object
 6   status_entrega         22 non-null     object
dtypes: int64(2), object(5)
memory usage: 1.3+ KB

⚠️ Valores Nulos:
id_entrega               0
id_venda                 0
transportadora           2
data_envio               1
data_entrega_prevista    2
data_entrega_real        5
status_entrega           0
dtype: int64

## 📈 Análise Consolidada

Vamos criar um resumo consolidado de todos os datasets para ter uma visão geral.

In [10]:
# Criar um DataFrame resumo
datasets_info = {
    'Dataset': ['Clientes', 'Produtos', 'Vendas', 'Logística'],
    'Registros': [len(clientes), len(produtos), len(vendas), len(logistica)],
    'Colunas': [len(clientes.columns), len(produtos.columns), len(vendas.columns), len(logistica.columns)],
    'Valores_Nulos': [
        clientes.isnull().sum().sum(),
        produtos.isnull().sum().sum(),
        vendas.isnull().sum().sum(),
        logistica.isnull().sum().sum()
    ]
}

resumo_df = pd.DataFrame(datasets_info)

print("📊 RESUMO CONSOLIDADO DOS DATASETS")
print("="*60)
display(resumo_df)

# Calcular totais
total_registros = resumo_df['Registros'].sum()
total_colunas = resumo_df['Colunas'].sum()
total_nulos = resumo_df['Valores_Nulos'].sum()

print(f"\n📋 TOTAIS:")
print(f"Total de registros: {total_registros}")
print(f"Total de colunas: {total_colunas}")
print(f"Total de valores nulos: {total_nulos}")

📊 RESUMO CONSOLIDADO DOS DATASETS
============================================================

     Dataset  Registros  Colunas  Valores_Nulos
0   Clientes         16        8              4
1   Produtos         20        7              2
2     Vendas         25        8              0
3  Logística         22        7             10

📋 TOTAIS:
Total de registros: 83
Total de colunas: 30
Total de valores nulos: 16

## 🎯 Próximos Passos

Com esta exploração inicial, identificamos:

1. **Volume de dados**: 83 registros distribuídos em 4 datasets
2. **Estrutura**: Diferentes esquemas para cada tipo de dado
3. **Qualidade**: Presença de valores nulos que precisam ser tratados

### 🔍 Recomendações para Análise Avançada:

- **Implementar validações com Great Expectations**
- **Verificar integridade referencial entre datasets**
- **Aplicar as 6 dimensões da qualidade de dados**
- **Criar pipelines de monitoramento contínuo**

### 📚 Recursos Relacionados:

- `Lab_DataOps_Governanca_Qualidade.ipynb` - Laboratório completo
- `Desafio_Final_DataOps.md` - Desafio prático
- `Conceitos.md` - Fundamentos teóricos