# 🚀 Lab DataOps: Governança e Qualidade de Dados com Great Expectations

## Objetivos do Laboratório

Neste laboratório prático, você irá:
- Implementar **testes de qualidade de dados** automatizados com **Great Expectations**
- Aplicar as **6 dimensões da qualidade** na prática
- Criar um **pipeline DataOps** com validações profissionais
- Simular cenários reais de **governança de dados**
- Gerar **relatórios de qualidade** automatizados

### Conceitos Aplicados
- **DataOps**: Automação e monitoramento contínuo
- **Governança**: Regras, políticas e responsabilidades
- **Qualidade**: Acurácia, Completude, Consistência, Pontualidade, Unicidade e Validade
- **Great Expectations**: Framework profissional para validação de dados

## 1. Configuração do Ambiente

In [1]:
import pandas as pd
from datetime import datetime, timedelta
import warnings
warnings.filterwarnings('ignore')

# Patch pandas para compatibilidade
if not hasattr(pd.DataFrame, 'iteritems'):
    pd.DataFrame.iteritems = pd.DataFrame.items

# Great Expectations
import great_expectations as gx
print(f"✅ Great Expectations: {gx.__version__}")
print(f"✅ Pandas: {pd.__version__}")
print("📊 Ambiente configurado com sucesso!")

✅ Great Expectations: 0.18.8
✅ Pandas: 2.1.1
📊 Ambiente configurado com sucesso!

## 2. Carregamento de Dados do CSV

In [9]:
# Carregar dados do CSV
df = pd.read_csv('datasets/clientes_lab.csv')

print("📋 Dataset carregado do CSV")
print(f"📊 Total de registros: {len(df)}")
print(f"📊 Colunas: {list(df.columns)}")
df.head()

📋 Dataset carregado do CSV
📊 Total de registros: 10
📊 Colunas: ['id_cliente', 'nome', 'email', 'telefone', 'data_cadastro', 'status', 'idade', 'estado']

,id_cliente,nome,email,telefone,data_cadastro,status,idade,estado
0,1,João Silva,joao@email.com,11999887766,2023-01-15,Ativo,25.0,SP
1,2,Maria Santos,maria.santos@gmail.com,11888776655,2023-02-20,Ativo,32.0,RJ
2,3,Pedro,pedro@invalid,119999,2023-03-10,Inativo,150.0,MG
3,4,Ana Costa,ana@email.com,11777665544,2023-04-05,Ativo,28.0,SP
4,1,João Silva,joao@email.com,11999887766,2023-01-15,Ativo,25.0,SP

## 3. Configuração do Great Expectations

In [10]:
# Inicializar Great Expectations
context = gx.get_context()
validator = context.sources.pandas_default.read_dataframe(df)
print("✅ Great Expectations configurado")

✅ Great Expectations configurado

## 4. Expectativas das 6 Dimensões da Qualidade

In [11]:
print("🎯 EXPECTATIVAS DAS 6 DIMENSÕES DA QUALIDADE")
print("=" * 50)

# 1. COMPLETUDE
print("\n📊 1. COMPLETUDE")
validator.expect_column_values_to_not_be_null("id_cliente")
validator.expect_column_values_to_not_be_null("nome")
validator.expect_column_values_to_not_be_null("email")
print("   ✅ OK")

# 2. UNICIDADE
print("\n🔑 2. UNICIDADE")
validator.expect_column_values_to_be_unique("id_cliente")
validator.expect_column_values_to_be_unique("email")
print("   ✅ OK")

# 3. VALIDADE
print("\n✅ 3. VALIDADE")
validator.expect_column_values_to_match_regex("email", r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")
validator.expect_column_values_to_be_between("idade", min_value=0, max_value=120)
validator.expect_column_values_to_be_in_set("status", ["Ativo", "Inativo", "Pendente"])
print("   ✅ OK")

# 4. CONSISTÊNCIA
print("\n🔄 4. CONSISTÊNCIA")
validator.expect_column_value_lengths_to_equal("telefone", 11)
validator.expect_column_values_to_be_dateutil_parseable("data_cadastro")
print("   ✅ OK")

# 5. PONTUALIDADE
print("\n⏰ 5. PONTUALIDADE")
data_limite = (datetime.now() - timedelta(days=730)).strftime("%Y-%m-%d")
validator.expect_column_values_to_be_between(
    "data_cadastro", 
    min_value=data_limite, 
    max_value=datetime.now().strftime("%Y-%m-%d")
)
print("   ✅ OK")

# 6. ACURÁCIA
print("\n🎯 6. ACURÁCIA")
validator.expect_column_values_to_be_in_set("estado", ["SP", "RJ", "MG", "RS", "BA", "PR", "SC", "GO"])
validator.expect_column_values_to_match_regex("telefone", r"^\d{11}$")
print("   ✅ OK")

print("\n🎉 Todas as expectativas criadas!")

🎯 EXPECTATIVAS DAS 6 DIMENSÕES DA QUALIDADE
==================================================

📊 1. COMPLETUDE

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

   ✅ OK

🔑 2. UNICIDADE

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

   ✅ OK

✅ 3. VALIDADE

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

   ✅ OK

🔄 4. CONSISTÊNCIA

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

   ✅ OK

⏰ 5. PONTUALIDADE

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

   ✅ OK

🎯 6. ACURÁCIA

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

   ✅ OK

🎉 Todas as expectativas criadas!

## 5. Validação

In [12]:
print("🔍 VALIDAÇÃO")
print("=" * 15)

result = validator.validate()

print(f"\n📊 RESULTADOS:")
print(f"   Total: {result.statistics['evaluated_expectations']}")
print(f"   Passou: {result.statistics['successful_expectations']}")
print(f"   Falhou: {result.statistics['unsuccessful_expectations']}")
print(f"   Taxa: {result.statistics['success_percent']:.1f}%")

if not result.success:
    print("\n❌ PROBLEMAS:")
    for r in result.results:
        if not r.success:
            col = r.expectation_config.kwargs.get('column', 'N/A')
            print(f"   • {col}")

🔍 VALIDAÇÃO
===============

Calculating Metrics:   0%|          | 0/53 [00:00<?, ?it/s]

📊 RESULTADOS:
   Total: 13
   Passou: 3
   Falhou: 10
   Taxa: 23.1%

❌ PROBLEMAS:
   • id_cliente
   • nome
   • email
   • email
   • email
   • idade
   • status
   • telefone
   • telefone
   • data_cadastro

## 6. Correção de Dados

In [13]:
print("🔧 CORREÇÃO DE DADOS")
print("=" * 20)

# Criar cópia para correção
df_corrigido = df.copy()

# 1. Remover duplicatas
df_corrigido = df_corrigido.drop_duplicates(subset=['id_cliente'])
print(f"✅ Duplicatas: -{len(df) - len(df_corrigido)}")

# 2. Remover registros com campos críticos vazios
df_corrigido = df_corrigido.dropna(subset=['nome', 'email'])
df_corrigido = df_corrigido[df_corrigido['nome'] != '']
print("✅ Campos vazios removidos")

# 3. Corrigir idades inválidas
df_corrigido.loc[(df_corrigido['idade'] < 0) | (df_corrigido['idade'] > 120), 'idade'] = None
print("✅ Idades corrigidas")

# 4. Padronizar status
df_corrigido.loc[df_corrigido['status'] == 'Cancelado', 'status'] = 'Inativo'
print("✅ Status padronizado")

print(f"\n📊 Original: {len(df)} → Corrigido: {len(df_corrigido)}")
df_corrigido.head()

🔧 CORREÇÃO DE DADOS
====================
✅ Duplicatas: -1
✅ Campos vazios removidos
✅ Idades corrigidas
✅ Status padronizado

📊 Original: 10 → Corrigido: 7

,id_cliente,nome,email,telefone,data_cadastro,status,idade,estado
0,1,João Silva,joao@email.com,11999887766,2023-01-15,Ativo,25.0,SP
1,2,Maria Santos,maria.santos@gmail.com,11888776655,2023-02-20,Ativo,32.0,RJ
2,3,Pedro,pedro@invalid,119999,2023-03-10,Inativo,NaN,MG
3,4,Ana Costa,ana@email.com,11777665544,2023-04-05,Ativo,28.0,SP
6,6,Lucia Oliveira,lucia@email.com,11555443322,2022-12-01,Ativo,45.0,BA

## 7. Re-validação

In [14]:
print("🔄 RE-VALIDAÇÃO")
print("=" * 15)

# Criar novo validator
validator2 = context.sources.pandas_default.read_dataframe(df_corrigido)

# Aplicar mesmas expectativas
validator2.expect_column_values_to_not_be_null("id_cliente")
validator2.expect_column_values_to_not_be_null("nome")
validator2.expect_column_values_to_not_be_null("email")
validator2.expect_column_values_to_be_unique("id_cliente")
validator2.expect_column_values_to_be_unique("email")
validator2.expect_column_values_to_match_regex("email", r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$")
validator2.expect_column_values_to_be_between("idade", min_value=0, max_value=120)
validator2.expect_column_values_to_be_in_set("status", ["Ativo", "Inativo", "Pendente"])
validator2.expect_column_value_lengths_to_equal("telefone", 11)
validator2.expect_column_values_to_be_dateutil_parseable("data_cadastro")
validator2.expect_column_values_to_be_between("data_cadastro", min_value=data_limite, max_value=datetime.now().strftime("%Y-%m-%d"))
validator2.expect_column_values_to_be_in_set("estado", ["SP", "RJ", "MG", "RS", "BA", "PR", "SC", "GO"])
validator2.expect_column_values_to_match_regex("telefone", r"^\d{11}$")

result2 = validator2.validate()

print("\n📊 COMPARAÇÃO")
print(f"Original: {result.statistics['success_percent']:.1f}%")
print(f"Corrigido: {result2.statistics['success_percent']:.1f}%")
melhoria = result2.statistics['success_percent'] - result.statistics['success_percent']
print(f"Melhoria: +{melhoria:.1f}pp")

🔄 RE-VALIDAÇÃO
===============

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/6 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/9 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/8 [00:00<?, ?it/s]

Calculating Metrics:   0%|          | 0/53 [00:00<?, ?it/s]

📊 COMPARAÇÃO
Original: 23.1%
Corrigido: 69.2%
Melhoria: +46.2pp

## 8. Relatórios

In [15]:
print("📈 RELATÓRIOS")
print("=" * 12)

try:
    context.build_data_docs()
    urls = context.get_docs_sites_urls()
    print("✅ Relatórios gerados!")
    for name, url in urls.items():
        print(f"   📋 {name}: {url}")
except Exception as e:
    print(f"⚠️ Erro: {str(e)[:50]}")

print("\n📋 RESUMO FINAL")
print("=" * 15)
print(f"📊 Original: {len(df)} registros - {result.statistics['success_percent']:.1f}%")
print(f"📊 Corrigido: {len(df_corrigido)} registros - {result2.statistics['success_percent']:.1f}%")
print(f"🎯 Melhoria: +{melhoria:.1f} pontos percentuais")
print(f"📉 Removidos: {len(df) - len(df_corrigido)} registros")
print("\n🎓 Lab DataOps concluído com sucesso!")

📈 RELATÓRIOS
============
✅ Relatórios gerados!
⚠️ Erro: 'list' object has no attribute 'items'

📋 RESUMO FINAL
===============
📊 Original: 10 registros - 23.1%
📊 Corrigido: 7 registros - 69.2%
🎯 Melhoria: +46.2 pontos percentuais
📉 Removidos: 3 registros

🎓 Lab DataOps concluído com sucesso!